###
GET http://localhost:8080/authorize?username=&password=

###
GET http://localhost:8080/authorize?username=Vlad&password=multiPass

###
GET http://localhost:8080/authorize?username=Ivan&password=suPass

###
GET http://localhost:8080/authorize?username=Maria&password=anyPass
